version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
  build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean package

artifacts:
  files:
    - target/*.jar
    - target/*.war