version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
      - echo "Logging in to AWS CodeArtifact..."
      - aws codeartifact login --tool maven --repository JJ-devops-cicd --domain my-company --domain-owner 249004168001 --region eu-central-1
  build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean package
artifacts:
  files:
    - target/*.jar
    - target/*.war