version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
      - echo "Getting CodeArtifact token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain my-company --domain-owner 249004168001 --region eu-central-1 --query authorizationToken --output text)
      - echo "Exported token for Maven to use."
  build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean package
artifacts:
  files:
    - target/*.jar
    - target/*.war
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no

